create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  tech_stack text[] not null default '{}',
  github_url text,
  live_url text,
  category text,
  featured_order int,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.contacts enable row level security;
alter table public.projects enable row level security;

create policy "Allow public inserts on contacts"
on public.contacts
for insert
to anon
with check (true);

create policy "Allow public reads on projects"
on public.projects
for select
to anon
using (true);

insert into public.projects (title, description, tech_stack, github_url, live_url, category, featured_order)
values
  (
    'Myzon - E-commerce App',
    'A complete MERN commerce experience with JWT authentication, streamlined cart flows, and order management.',
    array['React', 'Node.js', 'Express', 'MongoDB', 'JWT'],
    'https://github.com/yourusername/myzon',
    'https://example.com/myzon',
    'Full Stack',
    1
  ),
  (
    'Job Portal',
    'Role-based recruitment platform with job posting, application tracking, and secure REST APIs.',
    array['React', 'Redux', 'Node.js', 'Express', 'MongoDB'],
    'https://github.com/yourusername/job-portal',
    'https://example.com/job-portal',
    'Full Stack',
    2
  ),
  (
    'URL Shortener',
    'Backend-focused service that generates reliable short links and improves redirect performance with efficient database queries.',
    array['Node.js', 'Express', 'SQL', 'Redis'],
    'https://github.com/yourusername/url-shortener',
    'https://example.com/url-shortener',
    'Backend',
    3
  )
on conflict do nothing;

-- Create a public storage bucket named "resume" and upload your PDF.
